project:
  type: website
  output-dir: docs
  resources:
    - "data/**"

website:
  title: "Efficient Price, Inefficient Blocks"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: paper/paper.html
        text: Paper

format:
  html:
    theme: [cosmo, paper/styles.scss]
    css: paper/styles.scss
    toc: false
    self-contained: false
    smooth-scroll: true
    link-external-newwindow: true
    page-layout: full
    title-block-banner: true
    title-block-banner-color: "#F7931A"
